### PR TITLE
[GR-1181] Single-Lane Date Sort

### PR DESCRIPTION
**Pull request by avarsava**
- Only on Single-Lane TS for now
- the pdb breakpoint (_set_trace()_) in plot_builder is for demonstrating that the dataframe does indeed sort by date after the sort is run. Comment out the if and the breakpoint if you don't want to use pdb
- Available as both First and Second sort because I didn't know which would be better
- Available as Data Label for verifying that no sort happens in front end

### CODE REVIEW

**Comment by slazicoicr** [comment]
Hmm, playing around with this, there might be a deeper sorting issue going on (shudder). Below is the buggy situation. Reference (sort), Total Reads (second sort), and Run (colour by). The bug is that the data points are sorted first by Run and not Reference.

image

If I change to Reference (colour by), it looks right:

image

I have a vague memory of Heather fighting this sorting issue. I see that for Call Ready WGS, the sort and colour by are always the same. Using git blame leads me to #132.

**Comment by avarsava** [comment]
Yeah, iirc it's a side effect of needing to group data by shape- and colour-by in order to render the legend correctly. I also wrestled with it for a long time a few months ago. I don't think users have complained about it, it seems like it might make intuitive sense even if it doesn't make sense after thinking about it for a second.

**Comment by slazicoicr** [comment]
I think the lack of sorting you see might be because of this. As you cannot colour by date, setting it as first sort will not work.

Second sort by date works. If I sort and colour by Run and second sort by date I see expected behaviour. I think we should link sort and colour by to make this explicit:

image

**Comment by slazicoicr** [comment]
My approach from https://github.com/oicr-gsi/dashi/pull/217#issuecomment-639661108 was cheating, as I was sorting it by Run (which is the date). However, date sorting still works properly when I change sort and colour by to Project. By showing the run when I hover, i can see all points are properly sorted.

**Comment by avarsava** [comment]
Rebased onto develop, now that the sorting fix is in. It's really weird - on Single Lane TS select project BFS, sort by start date, show data label start date. It's SO CLOSE to being right, except that there's a bunch of stray 2018s in with the 2016s. I'll try to figure out why that's happening.

**Comment by avarsava** [comment]
Talked with @slazicoicr. He will investigate some spinoff work on looking at how the x-axis is constructed - Currently we are limited because the x-axis is just library names, so if one library has been run multiple times, all 3 dots get put on the x-axis value for their library at the earliest date. Investigating a composite x-axis in order to properly sort purely by date - if library name clustering is needed, library name sort option will be used.

**Pull request closed without merging**
