### PR TITLE
[GR-1272] Alert message when requested runs do not exist

### PR DESCRIPTION
**Pull request by slazicoicr**

### CODE REVIEW

**Comment by apmasell** [comment]
Nitpick: "No data for run" rather than "Doesn't exist".

**Review by apmasell — APPROVED** [review]

**Review by avarsava — COMMENTED** [review]
- Please add warning to SARS-CoV-2 report as well (it's not labeled as such but it's a single-lane report too)
- Code repetition could be reduced with a function taking initial["runs"], ALL_RUNS, and returning the Alert

**Comment by avarsava** [comment]
image
Could there be a `<br>` after the alert so it doesn't push over the JIRA buttons?

**Comment by slazicoicr** [comment]
Hmm, `<br>` does not seem to work (due to `row jira-buttons` div having flex display). How about putting the alert after the two boxes?

image

**Comment by avarsava** [comment]
> Hmm, `<br>` does not seem to work (due to `row jira-buttons` div having flex display). How about putting the alert after the two boxes?
> 
> image

I like it!

**Review by avarsava — APPROVED** [review]

**Pull request merged**
