### PR TITLE
Pool qc layout

### PR DESCRIPTION
**Pull request by ijafri26**
Updated layout for aesthetic of Pool Balancing QC Report as requested in Reporting Meeting. 
Added some filters to main page.

### CODE REVIEW

**Comment by slazicoicr** [comment]
Please use `git rebase` to clean up the commit history. "Intermediate commit" is not informative.

**Comment by callunity** [comment]
> Please use `git rebase` to clean up the commit history. "Intermediate commit" is not informative.

Seconding Savo's request for more informative commit messages, and please rebase onto master to clean up the merge conflicts.

**Comment by slazicoicr** [comment]
Hey @ijafri26,

Did the rebase happen? On my end I see a proliferation of duplicated commit messages:

image

**Comment by ijafri26** [comment]
Closing due to bad rebase, will open another PR from a different branch (Pool_Balancing_Layout)

**Pull request closed without merging**
