### PR TITLE
Allow specifying use of QC-ETL@master

### PR DESCRIPTION
**Pull request by callunity**
GR-994

### CODE REVIEW

**Review by apmasell — APPROVED** [review]

**Review by avarsava — APPROVED** [review]

**Comment by callunity** [comment]
(This didn't work as I had hoped, so the PR will remain open while I troubleshoot)

**Comment by callunity** [comment]
Updated. To test, add `USE_BLEEDING_EDGE_ETL=1` in your `.env` file, then do `docker-compose build && docker-compose up`. In the output from docker-compose up you should see that it installs `gsi-qc-etl@master` instead of the `gsi-qc-etl@v0.16.1` present in `requirements.txt`.

**Comment by avarsava** [comment]
Should this environment variable be documented in the README?

**Comment by callunity** [comment]
> Should this environment variable be documented in the README?

It could be. Right now the README only documents the required environment variables; I'll update it to describe all the possible environment variables (I'll include the one from #110 so @slazicoicr and I aren't writing over top of each other)

**Pull request merged**
