### PR TITLE
[GR-1136] Move caches to df_manipulation

### PR DESCRIPTION
**Pull request by avarsava**

### CODE REVIEW

**Comment by avarsava** [comment]
There's multiple caches in use - which should I use for DATAVERSION?

**Comment by apmasell** [comment]
How did we end up with multiple caches?

**Review by apmasell — APPROVED** [review]

**Comment by slazicoicr** [comment]
The Covid view pulls data from multiple caches (bedtools, samtools, kraken2).

**Comment by avarsava** [comment]
thanks @slazicoicr , andre helped me out on that and i pushed changes to include the dataversions

**Review by slazicoicr — APPROVED** [review]

**Pull request merged**
