### PR TITLE
[GR-1264] Fixed incorrect Coverage in Call Ready WGS Failed Sample table

### PR DESCRIPTION
**Pull request by slazicoicr**

### CODE REVIEW

**Review by avarsava — APPROVED** [review]

**Comment by avarsava** [comment]
Does 'None' deliver correctly to the MISO Run-Library QC page?

**Comment by slazicoicr** [comment]
The `None` feature is is Call Ready pages, which (I believe) do not have a link to MISO QC page.

**Review by avarsava — APPROVED** [review]
Might necessitate correcting the handling of None on the MISO side when I get to implementing QC in MISO for Call Ready reports but that can wait

**Comment by slazicoicr** [comment]
In this case, `None` mean Not Applicable. The QC metric in this column does not apply to the sample in this row.

**Review by asofmosq — APPROVED** [review]

**Pull request merged**
